add_newline = false

"$schema" = 'https://starship.rs/config-schema.json'
format = """${custom.is_home}${custom.is_folder}$directory$git_branch${custom.git_status}$character"""
right_format = """$all"""

[character]
success_symbol = "[âžœ](bold green)"
error_symbol = "[âœ—](bold red)"
vicmd_symbol = "[âœ“](bold green)"

[hostname]
ssh_only = true
format = "[$ssh_symbol](bold red) on [$hostname](bold green) "

[localip]
ssh_only = true
format = '@[$localipv4](bold red) '

[git_status]
format = '([$all_status$ahead_behind]($style) )'
disabled = false
modified = 'ðŸ“[($count)](yellow)'
untracked = 'ðŸ”[($count)](bold red)'
conflicted = 'ðŸš©'
stashed = 'ðŸ“¦'
deleted = 'ðŸ—‘ï¸'
behind = 'ðŸŒ'
ahead = 'ðŸŽðŸ’¨'
renamed = 'ðŸ‘…'

[custom.is_folder]
format = '[ï¼ ](bold blue)'
when = ''' test "$PWD" != "$HOME" '''

[custom.is_home]
format = '[ï€• ](bold blue)'
when = ''' test "$PWD" = "$HOME" '''

[custom.git_status]
command = '''
git_status=$(git status --porcelain)
# Untracked or Deleted (unstaged) files - Red
if echo ${git_status} | grep -qe '^?? ' -e '^[MARCDU ]D ' -e '^D[ UM]'; then
    echo -n $'\e[31mâ— '
fi

# Modified (unstaged) and Renamed files - Yellow
if echo ${git_status} | grep -qe '^[ MARC]M ' -e '^R[ MD] '; then
    echo -n $'\e[33mâ— '
fi

# Staged files (including Deleted) - Green
if echo ${git_status} | grep -qe '^A[ MDAU] ' -e '^M[ MD] ' -e '^UA' -e '^D '; then
    echo -n $'\e[32mâ— '
fi
'''
when = 'git rev-parse --is-inside-work-tree >/dev/null 2>&1'
format = '($output )'
